sudo: required
dist: xenial
language: cpp
git:
  submodules: false
matrix:
  include:
  - compiler: gcc
    env:
    - CXX_COMPILER=g++-5
    - CC_COMPILER=gcc-5
    - FC_COMPILER=gfortran-5
    - OMPI_CC=gcc-5
    - OMPI_FC=gfortran-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - g++-5
        - gfortran-5
        - ant
        - ant-optional
  - compiler: gcc
    env:
    - CXX_COMPILER=g++-6
    - CC_COMPILER=gcc-6
    - FC_COMPILER=gfortran-6
    - OMPI_CC=gcc-6
    - OMPI_FC=gfortran-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
        - gfortran-6
        - ant
        - ant-optional
  - compiler: gcc
    env:
    - CXX_COMPILER=g++-7
    - CC_COMPILER=gcc-7
    - FC_COMPILER=gfortran-7
    - OMPI_CC=gcc-7
    - OMPI_FC=gfortran-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - gfortran-7
        - ant
        - ant-optional
before_install:
- wget https://dl.bintray.com/sonarsource/SonarQube/org/sonarsource/scanner/cli/sonar-scanner-cli/3.2.0.1227/sonar-scanner-cli-3.2.0.1227-linux.zip
- unzip sonar-scanner-cli-3.2.0.1227-linux.zip
- export PATH=$PATH:$TRAVIS_BUILD_DIR/sonar-scanner-3.2.0.1227-linux/bin
- sonar-scanner --help
before_script:
- export FC=$FC_COMPILER
- export CC=$CC_COMPILER
- export CXX=$CXX_COMPILER
- export OMPI_CC
- export OMPI_FC
script:
- export CLAW_SRC=$(pwd)
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=$HOME/claw ..
- make
- make install
- make -j clean-transformation transformation test
- cd -
- "./scripts/check_license"
- "./scripts/check_author"
- "./scripts/check_lib_split"
- cd scripts
- "./run.shellcheck"
- cd ..
- export CLAW_BUILD=$(CLAW_SRC)/build
- export OMNI_HOME=$(CLAW_BUILD)/home
- if [[ "${TRAVIS_PULL_REQUEST_SLUG}" == "claw-project/claw-compiler" ]]; then sonar-scanner -Dsonar.login=$SONAR_TOKEN; fi
- if [[ "${TRAVIS_REPO_SLUG}" == "claw-project/claw-compiler" ]] && [[ "${TRAVIS_PULL_REQUEST_SLUG}" == "" ]]; then sonar-scanner -Dsonar.login=$SONAR_TOKEN; fi
notifications:
  email:
    on_success: never
    on_failure: never
